### ISSUE TITLE
Some objects are not getting properly parsed

### ISSUE THREAD

**Issue by Whitebock** [Whitebock/TelegramApi#2]
Arrays inside parsed objects are not getting parsed themselves.
For example, when using `getUserProfilePhotos`, the actual files will remain
stdObjects instead of `PhotoSize`.

**Comment by hexxone** [comment]
Solved it :)

[api.telegram.php.txt](https://github.com/Whitebock/TelegramBot-ApiWrapper/files/310232/api.telegram.php.txt)

**Comment by Whitebock** [comment]
Solved using https://github.com/Whitebock/TelegramBot-ApiWrapper/commit/a03cbe55eac76f8afb595f85634fc5ad91c1a644
